export const Messages : Record<string, string>={
SHOPS_PAGE_HEADER: "ADD SHOPS",
INVENTORY_PAGE_HEADER:"ADD INVENTORY",
PRODUCTS_PAGE_HEADER:"ADD PRODUCTS",
INVENTORY_ADDED_ALERT:"INVENTORY ADDED SUCCESSFULLY",
SHOP_NAME_LABEL:"ENTER THE SHOP NAME      : ",
INVENTORY_NAME_LABEL:"ENTER THE INVENTORY NAME :",
LOADER : "LOADING....",

PRODUCT_DETAILS_LABEL:'ENTER THE PRODUCT DETAILS',
NAME_OF_PRODUCT:'ENTER THE NAME :',
PRICE_OF_PRODUCT:'ENTER THE PRICE :',
QUANTITY_OF_PRODUCT:'ENTER THE QUANTIRY :',
ADD_PRODUCT:"ADD PRODUCT",
PRODUCT_ADDED_SUCCESSFULL:"PRODUCT ADDED SUCCESSFULLY",
ENTER_COUNTRY:"ENTER THE COUNTRY",
ENTERING_STATE:"ENTER THE STATE",
ENTERING_CITY:"ENTER THE CITY",
SHOP_ADDED_SUCCESSFULLY:"SHOP_ADDED_SUCCESSFULLY",

SEARCH_INVENTORY:"SEARCH INVENTORY",
SEARCH_SHOP : "SEARCH SHOP",

SHOP_NAME:"SHOP NAME",
INVENTORY_NAME:"INVENTORY NAME",


};